import cv2
notfiltering = cv2.imread('giraffe.jpg')
k = 25
filteringblur = cv2.blur(notfiltering, (k, k))
filteringgaussianblur = cv2.GaussianBlur(notfiltering, (k, k), 0)
filteringmedianblur = cv2.medianBlur(notfiltering, k)
filteringbilateralfilter = cv2.bilateralFilter(notfiltering, 49, 85, 95)
resim1 = cv2.putText(notfiltering, 'not-filtering', (1100, 100), 0, 3, (0, 0, 0), 10, cv2.LINE_AA)
resim2 = cv2.putText(filteringblur, 'filtering-blur', (1100, 100), 0, 3, (0, 0, 0), 10, cv2.LINE_AA)
resim3 = cv2.putText(filteringgaussianblur, 'filtering-gaussianblur', (700, 100), 0, 3, (0, 0, 0), 10, cv2.LINE_AA)
resim4 = cv2.putText(filteringmedianblur, 'filtering-medianblur', (750, 100), 0, 3, (0, 0, 0), 10, cv2.LINE_AA)
resim5 = cv2.putText(filteringbilateralfilter, 'filtering-bilateralfilter', (700, 100), 0, 3, (0, 0, 0), 10, cv2.LINE_AA)
s = 0.18
dim = (int(s*notfiltering.shape[1]), int(s*notfiltering.shape[0]))
resim1 = cv2.resize(notfiltering, dim, cv2.INTER_AREA)
resim2 = cv2.resize(filteringblur, dim, cv2.INTER_AREA)
resim3 = cv2.resize(filteringgaussianblur, dim, cv2.INTER_AREA)
resim4 = cv2.resize(filteringmedianblur, dim, cv2.INTER_AREA)
resim5 = cv2.resize(filteringbilateralfilter, dim, cv2.INTER_AREA)
cv2.imshow('not-filtering', resim1)
cv2.imshow('filtering-blur', resim2)
cv2.imshow('filtering-gaussianblur', resim3)
cv2.imshow('filtering-medianblur', resim4)
cv2.imshow('iltering-bilateralfilter', resim5)
cv2.waitKey(0)
cv2.imwrite('giraffe blur.jpg', filteringblur, [cv2.IMWRITE_JPEG_QUALITY, 100])
cv2.imwrite('giraffe GaussianBlur.jpg', filteringgaussianblur, [cv2.IMWRITE_JPEG_QUALITY, 100])
cv2.imwrite('giraffe medianBlur.jpg', filteringmedianblur, [cv2.IMWRITE_JPEG_QUALITY, 100])
cv2.imwrite('giraffe bilateralFilter.jpg', filteringbilateralfilter, [cv2.IMWRITE_JPEG_QUALITY, 100])